(function(g){var window=this;'use strict';var B2=function(a){a.publish("cardstatechange",a.xl()&&a.Lp()?1:0)},C2=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},xcb=function(a){var b=g.hm(a);
a=g.qm(a);return new g.Wl(b.x,b.y,a.width,a.height)},ycb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.ns(a,b,function(){g.os(e);c.apply(a,arguments)},d)},F2=function(a){a=g.Sa(a);
delete D2[a];g.Cc(D2)&&E2&&E2.stop()},Acb=function(){E2||(E2=new g.Qo(function(){zcb()},20));
var a=E2;a.isActive()||a.start()},zcb=function(){var a=g.Wa();
g.sc(D2,function(b){Bcb(b,a)});
g.Cc(D2)||Acb()},G2=function(a,b,c,d){g.cp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Bcb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Ccb(a,a.progress);a.progress==1?(a.j=0,F2(a),a.onFinish(),a.Ds()):a.isPlaying()&&a.dO()},Ccb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Dcb=function(a,b){g.ob.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},H2=function(a,b,c,d,e){G2.call(this,b,c,d,e);
this.element=a},Ecb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
H2.call(this,a,b,c,d,e)},Fcb=function(a){return Math.pow(a,3)},Gcb=function(a){return 3*a*a-2*a*a*a},Hcb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},I2=function(a){return a.baseUrl||null},J2=function(a,b){return g.$m(g.rl(a,b),function(c){return!!c})},Icb=function(a,b,c){function d(pa){var Z=pa.hovercardButton;
if(!Z)return null;Z=Z.subscribeButtonRenderer;if(!Z)return null;var R=f(Z.unsubscribedButtonText),W=f(Z.subscribedButtonText);if(Z.subscribed){var v=f(Z.subscriberCountWithUnsubscribeText);var U=f(Z.subscriberCountText)}else v=f(Z.subscriberCountText),U=f(Z.subscriberCountWithSubscribeText);var cb=null;if(pa.signinEndpoint){cb=C2(pa,"signinEndpoint","webNavigationEndpointData","url");if(!cb){var Ab,Va;cb=(Va=g.Q((Ab=Z.signInEndpoint)==null?void 0:Ab.commandMetadata,g.w1))==null?void 0:Va.url}if(!cb)return null}return R&&
(W||cb)?{subscribed:Z.subscribed,subscribeText:R,subscribeCount:v,unsubscribeText:W,unsubscribeCount:U,enabled:Z.enabled,signinUrl:cb,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var Z=[],R=pa.videoId;R&&Z.push("v="+R);(R=pa.playlistId)&&Z.push("list="+R);(pa=pa.startTimeSeconds)&&Z.push("t="+pa);return"/watch?"+Z.join("&")}}
function f(pa){if(!pa)return null;var Z=pa.simpleText;return Z?Z:pa.runs?g.rl(pa.runs,function(R){return R.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,G=null,H=null,N=null,M=null;if(h==="VIDEO")g.Q(l,g.Hx)?m=g.Q(l,g.Hx).url:(M=g.Q(l,g.dQ),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.Q(l,g.Hx)?m=g.Q(l,g.Hx).url:(M=g.Q(l,g.dQ),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=C2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((G=C2(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=C2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=C2(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:
null,V="";if(b.metadata){var fa=f(b.metadata);fa&&(V=fa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),fY:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,XF:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,v$:n,sessionData:X?{itct:X}:null,Rea:q,pE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:J2(b.impressionUrls||[],I2),l$:J2(b.hovercardShowUrls||[],I2),clickUrls:J2(l.loggingUrls||[],I2),visualElement:g.rw(b.trackingParams),productPrice:H,additionalFeesText:N,watchEndpoint:M||null}},Jcb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:J2(a.impressionUrls||[],I2),elements:J2(a.elements||[],function(d,e){return Icb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.rw(a.trackingParams));return c},Kcb=function(a){g.bU.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.FO(a)||g.HO(a);this.events=new g.sE(this);g.P(this,this.events);this.events.T(this.player,g.VC("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.WC("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.kc);this.events.T(window,"focus",this.Wca);this.load();var b=g.ie("STYLE");(g.ae("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.pe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Lcb=function(a){return a.player.getVideoData().Ff?"current":a.Z?"new":"current"},K2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},Mcb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=Jcb(f,Lcb(a))));L2(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.zw;d&&(c.postParams={ad_tracking:d});if(b=g.ULa(b))if(b=g.rd(b),b=g.nd(b))a.C=g.rr(b,c)},L2=function(a,b,c){c=c===void 0?!0:c;
a.player.nf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Ncb(a);c=[];d=new g.TC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.S({I:"div",S:"ytp-ce-shadow"}),g.xR(a.player,a.B.element,4),a.D=new g.Zx(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Ocb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.xR(a.player,f.element,4);var h=new g.TC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Pcb(a,f,e)}else g.Ew(new g.Ms("buildEndscreenElement null",
e))}a.player.jf(c);a.kc()}},Ncb=function(a){var b=g.uw(),c=g.vw();
c&&b&&a.endscreen.visualElement&&g.Nq(g.Qw)(void 0,c,b,a.endscreen.visualElement)},Ocb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Na:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.pE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:M2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:N2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Na:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.gp(b.title||"")},va:b.title},{I:"div",S:b.XF?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.S(a);break;case "PLAYLIST":a={I:"div",Na:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.pE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:M2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:N2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Na:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.gp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.S(a);break;case "CHANNEL":c={I:"div",Na:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.pE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Na:["ytp-ce-channel-title","ytp-ce-link"],X:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.gp(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Na:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:M2(b)}]};c=new g.S(c);var d=g.be(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Yo(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.TU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Na:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.pE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.gp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Na:["ytp-ce-website-goto","ytp-ce-link"],X:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:M2(b)},{I:"div",S:"ytp-ce-expanding-icon",X:Qcb(b.iconUrl)}]};c=new g.S(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Na:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.pE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.gp(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Na:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:M2(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.S(a)}b.isPlaceholder&&g.Yo(c.element,"ytp-ce-placeholder");return c},M2=function(a){if(a.fY)var b=a.fY.thumbnails;
return Qcb(b?b[b.length-1].url:null)},Qcb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Pcb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.Yo(b.element,"ytp-ce-force-expand"),O2(a,c.id,!0)):(g.$o(b.element,"ytp-ce-force-expand"),g.$o(b.element,"ytp-ce-element-hover"),O2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Rcb(a,b,c)});
b.listen("mouseleave",function(){Scb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Yo(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Tcb(a,c,m)});
b.listen("keypress",function(m){Tcb(a,c,m)});
b.listen("focus",function(){Rcb(a,b,c)});
b.listen("blur",function(){Scb(a,b,c)});
b.listen("touchstart",function(){Rcb(a,b,c)});
var l=g.de("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.$o(b.element,"ytp-ce-element-hover");g.$o(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=m.keyCode===9&&!m.shiftKey});
d(g.de("ytp-sb-subscribe",b.element));d(g.de("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Tcb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.Xo(d,"ytp-ce-element");){g.Xo(d,"subscribe-label")&&Ucb(a,b);
if(g.Xo(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.Xo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Scb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.Rea==="new")Ucb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.rd(N2(a,b.targetUrl)),c=g.nd(c),g.Ky(c,void 0,b.sessionData);else{var e=g.TO(a.player.U())||a.player.getVideoData().Ff,f=function(){var h=N2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.Xq(h);e&&n&&(n.v||n.list)?a.player.yp(n.v,l,n.list,!1,void 0,m||void 0):g.Jy(h,l)};
Ucb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},N2=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.aP(a)+b}else return"";return b},Rcb=function(a,b,c){g.Xo(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.Yo(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Qo(function(){g.Yo(b.element,"ytp-ce-element-hover")},200)).start():g.Yo(b.element,"ytp-ce-element-hover"),P2(a,c.l$),O2(a,c.id,!0))},Scb=function(a,b,c){g.$o(b.element,"ytp-ce-element-hover");
g.$o(b.element,"ytp-ce-force-expand");O2(a,c.id,!1)},O2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.bp(a.j[e].element,"ytp-ce-element-shadow-show",c)},P2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||K2(a))c&&c();else{b=Vcb(a,b);var e=0,f=!1,h=new g.Qo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Nu(b[a],d)}},Ucb=function(a,b,c){P2(a,b.clickUrls,c);
(a=g.vw())&&b.v$&&g.$w(a,b.visualElement)},Vcb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Wcb(b[d],c));return a},Wcb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Xcb=function(a){return typeof a==="string"?a:""},Q2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Ycb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},R2=function(a){return a.value?a.value:null},S2=function(a){if(!a)return null;
var b=g.rd(Xcb(a.value));b=g.nd(b);if(!b)return null;var c=Q2(a.target,Zcb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new Ycb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},$cb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},cdb=function(a){if(!a)return null;
var b=Q2(a.type,adb),c=Q2(a.trigger,bdb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=S2(a?a:null);return b?new $cb(b,c,a):null},ddb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},edb=function(a,b){return g.Mb(a.action,b)},fdb=function(a,b){this.context=a;
this.j=b},gdb=function(a){return a.customMessage?T2("div","iv-card-message",a.customMessage):""},U2=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},hdb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T2("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},T2=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.gp(c);return{I:a,X:b,va:c}},idb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.BE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.BE+");");c.dir=g.gp(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Na:b,X:c,V:d}},V2=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.sj.click,5)}},jdb=function(a,b){this.merchant=a;
this.price=b},kdb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},ldb=function(a,b){return b?b:kdb(a)?"current":"new"},W2=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.ob=!1;this.Wa=new Map;this.Za=new Map;this.context.J.addEventListener(g.VC("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.WC("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},X2=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.eO(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.ob=!1});
a.context.j.listen(b,"touchmove",function(){a.ob=!0})},mdb=function(a){var b;
return((b=g.Q(a,g.Hx))==null?0:b.url)?g.Q(a,g.Hx).url:(a=g.Q(a,g.dQ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},Y2=function(a,b,c){return{DZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
f3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
WM:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},ndb=function(a,b,c){W2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.La=this.Kb=this.C=this.isInitialized=!1;this.cards=[];this.yb=this.Z=this.Ma=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Cf=this.Ga=null;this.K=0;this.Fa=new g.Qo(function(){},c.W.bk?4E3:3E3);
g.P(this,this.Fa);this.fb=new g.Qo(function(){});
g.P(this,this.fb);this.Aa=new fdb(c,function(e,f,h,l,m,n){X2(d,e,f,h,l,m,n)});
this.Y=new g.S({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Na:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.P(this,this.Y);this.D=this.Y.element;this.Xa=new g.Zx(this.Y,330);g.P(this,this.Xa);this.Jb=g.de("iv-drawer-header-text",this.D);this.B=g.de("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Kb&&Z2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.C)&&$2(d)});
this.Ra=new g.sE(this);g.P(this,this.Ra);this.J.addEventListener("videodatachange",this.ou.bind(this))},odb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){Z2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){$2(a)});
var c=b.headerText;g.re(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.rw(b.trackingParams);a.N=g.rw(b.closeTrackingParams);a.Cf=g.rw(b.iconTrackingParams)},pdb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,sj:{},Op:null,Xj:e.trackingParams?g.rw(e.trackingParams):null,Cf:f&&f.trackingParams?g.rw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
BE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};a3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.nx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:b3(a,c,b,f),sponsored:!1,sj:Y2(f,e,f.command),Op:f.trackingParams?g.rw(f.trackingParams):null,Xj:e.trackingParams?g.rw(e.trackingParams):null,Cf:l&&l.trackingParams?g.rw(l.trackingParams):null,imageUrl:c3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.nx(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,BE:null,title:f.title?g.nx(f.title):"",customMessage:f.callToAction?g.nx(f.callToAction):"",url:g.Q(f.command,g.Hx).url?S2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.Hx).url}):null,onClickCommand:null};a3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:b3(a,c,b,e),sponsored:!1,sj:Y2(e,f,e.endpoint),Op:e.trackingParams?g.rw(e.trackingParams):null,Xj:f.trackingParams?g.rw(f.trackingParams):null,Cf:l&&l.trackingParams?g.rw(l.trackingParams):null,channelId:g.Q(e.endpoint,g.xQ).browseId,customMessage:e.customText?g.nx(e.customText):null,profileImageUrl:c3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.nx(e.channelName):"",metaInfo:[e.subscriberCountText?g.nx(e.subscriberCountText):""],url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.xQ).canonicalBaseUrl?g.Q(e.endpoint,g.xQ).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.xQ).browseId}),onClickCommand:null};a3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b3(a,c,b,e),sponsored:!1,sj:Y2(e,f,e.action),Op:e.trackingParams?g.rw(e.trackingParams):null,Xj:f.trackingParams?g.rw(f.trackingParams):null,Cf:l&&l.trackingParams?g.rw(l.trackingParams):null,iI:c3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.nx(e.customMessage):null,playlistVideoCount:g.nx(e.playlistVideoCount),title:e.playlistTitle?g.nx(e.playlistTitle):"",metaInfo:[e.channelName?g.nx(e.channelName):
"",e.videoCountText?g.nx(e.videoCountText):""],url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mdb(e.action)}),onClickCommand:null};a3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.nx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b3(a,c,b,e),sponsored:!1,sj:Y2(e,f,e.action),Op:e.trackingParams?g.rw(e.trackingParams):null,Xj:f.trackingParams?g.rw(f.trackingParams):null,Cf:l&&l.trackingParams?g.rw(l.trackingParams):null,iI:c3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.nx(e.lengthString):null,customMessage:e.customMessage?g.nx(e.customMessage):null,title:e.videoTitle?g.nx(e.videoTitle):"",metaInfo:[e.channelName?g.nx(e.channelName):
"",e.viewCountText?g.nx(e.viewCountText):""],isLiveNow:!!e.badge,url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mdb(e.action)}),onClickCommand:null};a3(a,b)}}}}}a.K++},c3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},b3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},rdb=function(a,b){if(b=qdb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.wf.id),g.pe(b.QO),g.Rb(a.cards,b),a.nJ(),d3(a)},Z2=function(a,b,c){if(!a.C){a.Xa.show();
a.Va=new g.Qo(function(){g.Yo(a.context.J.getRootNode(),g.uX.IV_DRAWER_OPEN)},0);
a.Va.start();a.Ra.T(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.vw();d&&a.Ga&&a.N&&g.Yw(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.H_||(f.H_=!0,sdb(a.context.logger,f.wf.sj.DZ,b)),d&&g.Yw(d,[f.wf.Op]);B2(a.J);c&&(a.G=new g.Qo(function(){a.Ma=a.Z;a.yb.focus()},330),a.G.start())}},$2=function(a){a.C&&(a.Xa.hide(),g.vs(a.Ra),g.$o(a.context.J.getRootNode(),g.uX.IV_DRAWER_OPEN),a.C=!1,B2(a.J),a.G&&a.G.stop(),a.G=new g.Qo(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},tdb=function(a){g.Zo(a.Ib(),
[g.uX.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.xR(a.J,a.D,5);a.aJ();a.Z=g.de("ytp-cards-button",a.J.getRootNode());a.yb=g.de("iv-drawer-close-button",a.D);a.isInitialized=!0},udb=function(a){a.qa.push(g.ev("iv-teaser-shown",a.R6,a));
a.qa.push(g.ev("iv-teaser-hidden",a.O$,a));a.qa.push(g.ev("iv-teaser-clicked",a.Q6,a));a.Ab=!0},vdb=function(a,b){var c;
return b.onClickCommand&&((c=g.Q(b.onClickCommand,g.mab))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.ra=b,!0):!1},wdb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.wP(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.Q(h[0],g.TRa))==null?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},a3=function(a,b){if(!vdb(a,b)||wdb(a,b)){var c=xdb(a,b);
if(c){var d={wf:b,QO:c.element,H_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||udb(a),rdb(a,b.id),c=a.findLastIndex(d),g.Xb(a.cards,c,0,d));else{a.isInitialized||tdb(a);rdb(a,b.id);var e=a.findLastIndex(d);g.Xb(a.cards,e,0,d);c.Ja(a.B,e);a.nJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,d3(a),ydb(a,d),Z2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&zdb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){zdb(a,d)}),d3(a))}}},xdb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=idb(b);c={I:"div",Na:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?R2(b.url)||"":""},V:[U2(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[T2("h2",void 0,b.title),d]}]}]};c=new g.S(c);V2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Na:["iv-card","iv-card-channel"],V:[{I:"a",Na:["iv-click-target"],X:{href:R2(b.url)||"","data-ytid":b.channelId},V:[U2(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[gdb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},hdb(b)]}]}]};c=new g.S(c);V2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Na:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:R2(b.url)||""},V:[U2(b.iI,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[gdb(b),T2("h2","iv-card-primary-link",b.title),hdb(b)]}]}]};
c=new g.S(c);V2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=b.offers.length!=0;c=["iv-card"];d="";var f=idb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?R2(b.url)||"":"";c={I:"div",Na:c,X:{tabindex:"0"},V:[{I:"a",Na:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[T2("h2",d,b.title),f]}]}]};c=new g.S(c);d=g.ie("span");g.re(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Bd(d,"adInfo");V2(a,g.ce("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Na:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Na:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:((c=b.url)==null?void 0:R2(c))||""},V:[U2(b.iI,d),{I:"div",S:"iv-card-content",V:[gdb(b),T2("h2","iv-card-primary-link",b.title),hdb(b),f]}]}]};c=new g.S(e);V2(a,g.ce("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Adb=function(a){if(a.j)return a.j.wf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.sl(a.cards,function(c){return c.wf.type==="productListing"})}return g.sl(a.cards,function(c){return c.wf.type==="productListing"})},d3=function(a){g.bp(a.J.getRootNode(),"ytp-cards-shopping-active",Adb(a))},zdb=function(a,b){if(!g.Xo(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.vw(),d=a.j?a.j.wf.Cf:a.Cf;
c&&d&&g.Zw(c,[d]);a.j=b;d3(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.wf.teaserDurationMs&&a.J.uC(!0,{teaserText:b.wf.teaserText,durationMs:b.wf.teaserDurationMs,onClickCommand:b.wf.onClickCommand});a.fb.isActive()||((!a.C||!a.Fa.isActive()&&a.La)&&ydb(a,b),a.fb.start(910+b.wf.teaserDurationMs))}},ydb=function(a,b){a.Y.Gb?(b=new G2([0,
a.B.scrollTop],[0,b.QO.offsetTop],600,Gcb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.jx(a.Y,!0),a.B.scrollTop=b.QO.offsetTop,g.jx(a.Y,!1))},e3=function(a){return a.j&&a.j.wf?a.j.wf:a.cards[0]&&a.cards[0].wf?a.cards[0].wf:null},qdb=function(a,b){return g.Mb(a.cards,function(c){return c.wf.id===b})},f3=function(a,b,c){W2.call(this,a,b);
this.annotation=c;this.isActive=!1},Bdb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},g3=function(a,b,c){f3.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Cdb=function(a,b){var c=c===void 0?0:c;
var d=xcb(b).width;g.fm(b,d);c=new Ecb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Fcb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.rm(b,!0)});
c.play()},Fdb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Na:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Na:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.TU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Na:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Na:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.rm(h,!1);var l=a.createElement({I:"div",Na:["branding-context-container-outer"]});l.appendChild(h);g.Zl(l,"right",b.image_width+"px");g.ke(a.Ib(),l);a.C=new g.Qo(function(){Ddb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){Edb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},Edb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.qm(b);a.j||(b.style.width=g.em(f.width,!0),c.style.width=g.em(f.width,!0));g.Zl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Zl(d,"right","1px");a.D=!0;g.rm(b,!0);a.G=new g.Qo(function(){g.Yo(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},Ddb=function(a,b,c){g.$o(a.Ib(),"iv-branding-active");
a.K=new g.Qo(function(){g.rm(b,!1);a.j||(c.style.width=g.em(0,!0))},250);
a.K.start();a.D=!1},Gdb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Hdb=function(a,b,c){f3.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Na:["iv-promo-contents"]});this.G=new g.Qo(function(){d.j.setAttribute("aria-hidden","true");g.rm(d.C,!1);g.rm(d.B,!0)},700,this);
g.P(this,this.G)},Kdb=function(a,b,c){c.stopPropagation();
Idb(a);Jdb(a,b);a.j.focus()},Ldb=function(a){a.isCollapsed||a.Z||a.D||(g.Yo(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Idb=function(a){a.G.stop();
a.isCollapsed&&(g.ap(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.rm(a.B,!1),g.rm(a.C,!0))},Jdb=function(a,b){a.D||(a.D=g.Le(function(){Mdb(this);
Ldb(this)},b,a))},Mdb=function(a){a.D&&(g.Ja.clearTimeout(a.D),a.D=null)},Ndb=function(a){this.J=a},sdb=function(a,b,c){b&&(c?h3(a,b.map(function(d){return g.qo(d,c)})):h3(a,b))},h3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Nu(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},Odb=function(a){g.bU.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new Ndb(this.player);this.D=new g.sE(this);this.G=this.N=null;this.events=new g.sE(this);this.Yg=this.Y=this.j=null;this.ra=[];g.P(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.S6,this);this.subscribe("resize",this.ML,this);this.player.U().La.subscribe("vast_info_card_add",this.X0,this);g.P(this,this.events);this.Aa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.S({I:"div",Na:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.xR(this.player,this.B.element,4);this.B.hide();this.C=new g.S({I:"div",Na:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Aa);this.C.element.appendChild(a);this.Av()&&this.load();var c=this.createElement({I:"style"});(g.ae("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.pe(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Pdb=function(a){a=a.createElement({I:"div",
Na:["annotation","annotation-type-custom"]});g.rm(a,!1);return a},Qdb=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.jx(a.B,b);g.jx(a.C,b)},Rdb=function(a,b,c){a.Z=!0;
a.G=g.rr(b,c)},Sdb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Qa(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Sdb(a,e))}return c},Wdb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.gr(h)&&h.responseXML?h.responseXML:null)&&Tdb(a,h)}};
g.Us()&&(d.onFinish=Udb(a,d.onFinish));d.postParams={ic_only:"1"};Vdb(d,c);a.Z=!0;g.rr(b.Xa,d)}}},Vdb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.sJ&&(a.postParams.ic_coll=b.sJ);b.RO&&(a.postParams.ic_xml=b.RO);b.bN&&(a.postParams.ic_track=b.bN)},Xdb=function(a){var b=new g.S({I:"div"});
g.rm(b.element,!1);var c=new ndb(a.player,b.element,i3(a));g.P(c,b);b.Ja(a.B.element);c.SH();return c},Zdb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.qa=!0,Ydb(a,b),b.headerText&&a.Yg&&(c=g.nx(b.headerText),a.Yg.setAttribute("title",c))},i3=function(a){if(!a.Y){var b=new Hcb(a);
g.P(a,b);var c=new g.ok(a);g.P(a,c);a.Y=new Gdb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Gj)}return a.Y},Tdb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.vw();if(e){var f=g.uw();f&&g.Nq(g.Pw)(void 0,e,f,[g.rw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Sdb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=Q2(f.type,$db),p=Q2(f.style,aeb),q=Xcb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=cdb;if(t==null)var u=null;else if(g.Oa(t)){l=[];for(var y=g.w(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var G=f(t);u=G?[G]:[]}e=m&&n?new ddb(m,n,p,u,r):null}else e=null}catch(fa){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=Pdb(f),N=null;switch(l.type){case "branding":if(f.player.U().Dd)break;f.B.element.appendChild(H);N=new g3(H,i3(f),l);break;case "promotion":g.xR(f.player,H,4),N=new Hdb(H,i3(f),l)}N&&N.SH();if(f=N)g.P(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=Xdb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={DZ:f.impression,click:f.click,close:f.close,f3:f.teaser_impression,WM:f.teaser_click},l=e.tracking_params||{},N=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,sj:f,Op:l.card?g.rw(l.card):null,Xj:l.teaser?g.rw(l.teaser):null,Cf:l.icon?g.rw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,sj:f,
Op:l.card?g.rw(l.card):null,Xj:l.teaser?g.rw(l.teaser):null,Cf:l.icon?g.rw(l.icon):null,iI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a3(H,c);break;case "productListing":e.signin_url&&(N=S2({target:"current",value:e.signin_url}));M=[];for(var X=e.offers||[],V=0;V<X.length;V++)M.push(new jdb(g.Ud(X[V].merchant),
g.Ud(X[V].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,sj:f,Op:l.card?g.rw(l.card):null,Xj:l.teaser?g.rw(l.teaser):null,Cf:l.icon?g.rw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,BE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Upa:N,Tpa:e.signin_title?e.signin_title:void 0,Spa:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};a3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,sj:f,Op:l.card?g.rw(l.card):
null,Xj:l.teaser?g.rw(l.teaser):null,Cf:l.icon?g.rw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,BE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,sj:f,Op:l.card?g.rw(l.card):null,Xj:l.teaser?g.rw(l.teaser):null,Cf:l.icon?g.rw(l.icon):null,iI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},a3(H,c)}}else odb(a.j,e);c=!0}}c&&
(B2(a.player),a.ML())},Ydb=function(a,b){var c=!1;
a.j||(a.j=Xdb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(pdb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.EQ(f)||(c=a.j,d=b.headerText?g.nx(b.headerText):"",g.re(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.rw(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.rw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Cf=b.icon.infoCardIconRenderer.trackingParams?g.rw(b.icon.infoCardIconRenderer.trackingParams):null,a.ML());B2(a.player)}},beb=function(a,b,c,d,e){if(!a.player.U().Dd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.xQ)&&g.Q(b.navigationEndpoint,g.xQ).browseId&&f.push(new $cb("openUrl","click",new Ycb("/channel/"+g.Q(b.navigationEndpoint,g.xQ).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.yQ)){d.channel_id=g.Q(b.subscribeButton,g.yQ).channelId;var l;b=g.Q(b.subscribeButton,g.yQ);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.nx(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.nx(b.subscriberCountText))):(b.subscriberCountText&&(e=g.nx(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.nx(b.subscriberCountWithSubscribeText)));var m,n=((m=g.Q((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.w1))==null?void 0:m.url)||"";l={subscribeText:g.nx(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.nx(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new ddb(c,"branding","branding",f,d);l=Pdb(a);a.B.element.appendChild(l);f=new g3(l,i3(a),f);f.SH();g.P(f,f);a.K[c]=f}},Udb=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.Ka()||a.ra.push(g.Jo.Wi(function(){b.apply(null,g.x(c))}))}},ceb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.pR.prototype.uC=g.ba(35,function(a,b){var c=g.BU(this.Bb());c&&c.uC(a,b)});
var D2={},E2=null;g.Xa(G2,g.cp);g.k=G2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;F2(this);this.startTime=a=g.Wa();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.DL();this.Un("play");this.isPaused()&&this.Un("resume");this.j=1;var b=g.Sa(this);b in D2||(D2[b]=this);Acb();Bcb(this,a);return!0};
g.k.stop=function(a){F2(this);this.j=0;a&&(this.progress=1);Ccb(this,this.progress);this.onStop();this.Ds()};
g.k.pause=function(){this.isPlaying()&&(F2(this),this.j=-1,this.Un("pause"))};
g.k.ya=function(){this.j==0||this.stop(!1);this.Un("destroy");G2.Of.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.dO=function(){this.Un("animate")};
g.k.Un=function(a){this.dispatchEvent(new Dcb(a,this))};
g.Xa(Dcb,g.ob);g.Xa(H2,G2);H2.prototype.C=function(){};
H2.prototype.dO=function(){this.C();H2.Of.dO.call(this)};
H2.prototype.Ds=function(){this.C();H2.Of.Ds.call(this)};
H2.prototype.DL=function(){this.C();H2.Of.DL.call(this)};
g.Xa(Ecb,H2);Ecb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(Hcb,g.O);g.k=Hcb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Ta)(c,d||this.B);a=g.ns(a,b,c);this.j.push(a);return a};
g.k.pG=function(a,b,c,d){c=(0,g.Ta)(c,d||this.B);a=ycb(a,b,c);this.j.push(a);return a};
g.k.Nc=function(a){g.os(a);g.Rb(this.j,a)};
g.k.removeAll=function(){g.os(this.j);this.j.length=0};
g.k.ya=function(){this.removeAll();g.O.prototype.ya.call(this)};g.z(Kcb,g.bU);g.k=Kcb.prototype;g.k.load=function(){g.bU.prototype.load.call(this);if(!K2(this)){var a=g.VLa(this.player.getVideoData());a?(a=Jcb(a,Lcb(this)),L2(this,a,!1)):Mcb(this)}};
g.k.unload=function(){L2(this,null);this.C&&(this.C.abort(),this.C=null);g.bU.prototype.unload.call(this)};
g.k.Xh=function(a,b){return K2(this)?a==="loadCustomEndscreenRenderer"?(a=Jcb(b,"new"),L2(this,a),!0):null:null};
g.k.getOptions=function(){return K2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.kc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<deb.length;f++){var h=Math.abs(b.width-deb[f]);if(e===-1||d>=h)e=f,d=h}d=eeb[e];this.B&&g.Zl(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.pm(e.element,m,f);g.fm(e.element,n,p);g.ap(e.element,feb);m>256||f>256?g.Yo(e.element,"ytp-ce-large-round"):m>96||f>96?g.Yo(e.element,"ytp-ce-medium-round"):g.Yo(e.element,"ytp-ce-small-round");g.ap(e.element,geb);m=h.left+h.width/2;h=h.top+l/2;g.Yo(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ap(e.element,eeb);g.Yo(e.element,d);(e=g.be(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Zl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")P2(this,this.endscreen.impressionUrls),(a=g.vw())&&this.endscreen.visualElement&&g.Xw(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Yo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Yo(b,"ytp-ce-shown");P2(this,c.impressionUrls);(b=g.vw())&&g.Xw(b,c.visualElement);this.player.U().N&&this.player.ib("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.$o(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.$o(b,"ytp-ce-shown");this.player.U().N&&this.player.ib("endscreenelementhidden",a)}};
g.k.Wca=function(a){var b=this;a.target===window&&(new g.Qo(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.ap(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var deb=[346,426,470,506,570,640,853,1280,1920],eeb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),geb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],feb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Zcb={pha:"current",Sja:"new"};var adb={CLOSE:"close",Xja:"openUrl",SUBSCRIBE:"subscribe"},bdb={Xga:"click",CLOSE:"close",qia:"hidden",Kka:"rollOut",Lka:"rollOver",Vka:"shown"};ddb.prototype.Be=function(){var a=edb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var aeb={gga:"anchored",y4:"branding",CHANNEL:"channel",oha:"cta",tia:"highlightText",hja:"label",PLAYLIST:"playlist",POPUP:"popup",gla:"speech",SUBSCRIBE:"subscribe",sla:"title",VIDEO:"video",ama:"website"},$db={y4:"branding",Lga:"card",Aha:"drawer",sia:"highlight",xja:"marker",tka:"promotion",TEXT:"text",Ema:"widget"};g.z(W2,g.O);g.k=W2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.TC(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.Za.set(a,e);this.context.J.jf([a],1)};
g.k.SH=function(){this.context.B.subscribe("resize",this.nJ,this)};
g.k.Ib=function(){return this.element};
g.k.eO=function(a,b,c,d,e,f){if(this.ob)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.pe(this.Ib())};
g.k.nJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R2(a);if(f){var h=ldb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Ff||!1,n=g.Xq(f||"");m&&n&&(n.v||n.list)?e.context.J.yp(n.v,b,n.list,!1):g.Ky(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);h3(this.context.logger,c,l,d);kdb(f)||(c=g.vw(),d=b.itct,c&&d&&g.$w(c,g.rw(d)))}};
g.k.ya=function(){this.Wa.clear();this.Za.clear();g.O.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.z(ndb,W2);g.k=ndb.prototype;g.k.ou=function(){this.ra&&a3(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.qm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.nJ=function(){var a=this.isAvailable();g.rm(this.Ib(),a);g.bp(this.context.J.getRootNode(),g.uX.IV_DRAWER_ENABLED,a);B2(this.J)};
g.k.destroy=function(){this.J.uC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.fv(this.qa);g.vs(this.Ra);this.Va&&this.Va.dispose();this.G&&this.G.dispose();W2.prototype.destroy.call(this)};
g.k.aJ=function(){var a=this,b=g.de("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.S7,this);this.context.j.listen(this.B,"touchend",function(){a.Fa.start()});
this.context.j.listen(this.B,"scroll",this.p8,this);this.context.B.subscribe("onHideControls",function(){a.La=!0});
this.context.B.subscribe("onShowControls",function(){a.La=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.La=g.Xo(a.J.getRootNode(),"ytp-autohide")});
this.qa.push(g.ev("iv-button-shown",this.N$,this));this.qa.push(g.ev("iv-button-hidden",this.M$,this));udb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Nb(this.cards,function(c){return a.wf.startMs>c.wf.startMs||a.wf.startMs===c.wf.startMs&&a.wf.timestamp>=c.wf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.S7=function(){if(this.C){h3(this.context.logger,e3(this).sj.close);var a=g.vw();a&&this.N&&g.$w(a,this.N);$2(this)}};
g.k.p8=function(){g.bp(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.N$=function(){var a=g.vw(),b=e3(this);b=b?b.Cf:this.Cf;a&&b&&g.Yw(a,[b])};
g.k.M$=function(){var a=g.vw(),b=e3(this);b=b?b.Cf:this.Cf;a&&b&&g.Zw(a,[b])};
g.k.R6=function(){var a=e3(this);h3(this.context.logger,a.sj.f3);var b=g.vw();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Xj&&c.push(a.Xj);a.Cf&&c.push(a.Cf);c.length>0&&g.Yw(b,c)}else g.Yw(b,[a.Xj,a.Cf])};
g.k.O$=function(){var a=g.vw(),b=e3(this);a&&b&&g.Zw(a,[b.Xj])};
g.k.Q6=function(a){var b=e3(this),c=g.vw();this.j?a?(a=this.context.logger,h3(a,b.sj.WM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Xj&&g.$w(c,b.Xj)):(a=this.context.logger,h3(a,b.sj.WM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Cf&&g.$w(c,b.Cf)):(a=this.context.logger,h3(a,b.sj.WM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Cf&&g.$w(c,this.Cf))};g.z(f3,W2);f3.prototype.SH=function(){W2.prototype.SH.call(this);Bdb(this)};
f3.prototype.show=function(){W2.prototype.show.call(this);var a=g.vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Yw(a,[g.rw(b.itct)])};
f3.prototype.hide=function(){W2.prototype.hide.call(this);var a=g.vw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Zw(a,[g.rw(b.itct)])};g.z(g3,f3);
g3.prototype.Ry=function(){g.Yo(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Na:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.rm(this.B,!1);var b=this.createElement({I:"button",Na:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.Be();c&&X2(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||Fdb(this,
a)};
g3.prototype.show=function(){if(!this.isActive&&(f3.prototype.show.call(this),this.N||(this.Ry(),this.N=!0),g.rm(this.Ib(),!0),this.isActive=!0,this.B)){try{Cdb(this,this.B)}catch(a){}g.Yo(this.context.J.getRootNode(),"ytp-branding-shown")}};
g3.prototype.hide=function(){this.isActive&&(f3.prototype.hide.call(this),g.rm(this.Ib(),!1),this.isActive=!1,g.$o(this.context.J.getRootNode(),"ytp-branding-shown"))};
g3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);f3.prototype.destroy.call(this)};g.z(Hdb,f3);g.k=Hdb.prototype;
g.k.Ry=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.Be(),f=b.image_url;if(f){var h=this.createElement({I:"div",Na:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&X2(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Jd(f,R2(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Na:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Na:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&X2(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.Yo(this.j,"iv-click-target");e&&X2(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Na:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.Yo(this.j,"iv-click-target"),e&&X2(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Na:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){Kdb(a,5E3,q)});
c.appendChild(this.B);g.rm(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.O9,this);this.context.j.listen(this.Ib(),"mouseout",this.N9,this);this.context.j.listen(this.Ib(),"touchend",function(q){Kdb(a,5E3,q)});
this.C=this.createElement({I:"button",Na:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.J9:this.I9,this);c.appendChild(this.C);g.Zo(this.Ib(),d);h&&(g.ke(this.Ib(),h),n&&h.appendChild(n));g.ke(this.Ib(),this.N);g.ke(this.Ib(),c)};
g.k.show=function(){this.isActive||(f3.prototype.show.call(this),this.Y||(this.Ry(),this.Y=!0),g.rm(this.Ib(),!0),g.Le(function(){g.$o(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,Mdb(this),Idb(this),Jdb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Yo(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.eO=function(a,b,c,d,e,f){return this.isCollapsed?!1:f3.prototype.eO.call(this,a,b,c,d,e,f)};
g.k.O9=function(a){this.Z=!0;Kdb(this,500,a)};
g.k.N9=function(){this.Z=!1;Ldb(this)};
g.k.I9=function(a){a.stopPropagation();this.hide()};
g.k.J9=function(a){a.stopPropagation();Mdb(this);this.isCollapsed=!0;g.Yo(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();f3.prototype.destroy.call(this)};g.z(Odb,g.bU);g.k=Odb.prototype;g.k.Xh=function(a,b){if(!ceb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.a1(b))&&Tdb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(rdb(this.j,b),B2(this.player)),!0}return null};
g.k.getOptions=function(){return ceb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Av=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.SQ(b)||g.fR(this.player.app)?!1:c===1&&!b.q1||a.La.get(b.videoId)||g.FQ(b)||g.GQ(b)?!0:!1};
g.k.ML=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.pm(this.C.element,a.width,a.height);g.fm(this.C.element,a.left,a.top)}if(this.j){var b=this.player.qo();a=this.j;b=b.width;g.bp(a.D,"iv-drawer-small",b<=426);g.bp(a.D,"iv-drawer-big",b>=1280)}};
g.k.S6=function(a){Qdb(this,a.state);g.T(a.state,2)&&(this.xl()&&this.Lp()&&this.player.getPresentingPlayerType()!==2&&this.vC(!1),this.uC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.gr(h)&&h.responseXML?h.responseXML:null)&&(Tdb(b,h),g.Yo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.bU.prototype.load.call(this);Qdb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Us()&&(a=Udb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().La.get(d);f&&Vdb(e,f);f=f&&(f.RO||f.sJ);if(!c.Yv||f)c.Xa?Rdb(this,c.Xa,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.EQ(h))&&!b.qa&&Zdb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.xR(this.player,this.C.element,4);this.ML();(f=g.FQ(c))&&Ydb(this,f);(f=g.GQ(c))&&f.featuredChannel&&beb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Yg=g.de("ytp-cards-button",this.player.getRootNode());g.EQ(c)&&Zdb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&Rdb(this,b.Xa,a)};
g.k.unload=function(){this.player.nf("annotations_module");for(var a=g.w(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,B2(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.bU.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.X0=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Wdb(this):this.load())};
g.k.xl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.qa};
g.k.Lp=function(){return!!this.j&&this.j.C};
g.k.vC=function(a,b,c){b=b===void 0?!1:b;this.xl();this.j&&(a?c?Z2(this.j,c,b):Z2(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):$2(this.j))};
g.k.uC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.U().La.unsubscribe("vast_info_card_add",this.X0,this);g.$o(this.player.getRootNode(),g.uX.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Jo,c=0,d=a.length;c<d;c++)b.jk(a[c]);this.ra.length=0;g.bU.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.aU("annotations_module",Odb);g.aU("creatorendscreen",Kcb);})(_yt_player);
